Starting up server ...
Connection request from ('127.0.0.1', 44896)
Started thread for client ('127.0.0.1', 44896)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message received ...
Connection request from ('127.0.0.1', 44985)
Started thread for client ('127.0.0.1', 44985)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message from server ...
Message from server ...
Message received ...
Connection closed from client ...
Connection closed at TCP level ...
disconnect
Inside disconnect
a
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "websocket_server.py", line 253, in run
    self.server.client_thread_closed(self)
  File "websocket_server.py", line 393, in client_thread_closed
    self.sendall(json.dumps(message), 'text')
  File "websocket_server.py", line 454, in sendall
    "message": self.usermap[str(messageObj.get('message'))] + " has disconnected"
KeyError: 'a'

Connection closed at TCP level ...
disconnect
Inside disconnect
abhidevmumbai
Connection request from ('127.0.0.1', 45090)
Started thread for client ('127.0.0.1', 45090)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message received ...
Connection closed at TCP level ...
disconnect
Inside disconnect
abhidevmumbai
Connection request from ('127.0.0.1', 45157)
Started thread for client ('127.0.0.1', 45157)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message received ...
Connection closed at TCP level ...
disconnect
Inside disconnect
abhidevmumbai
Connection request from ('127.0.0.1', 45246)
Started thread for client ('127.0.0.1', 45246)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message received ...
Connection closed at TCP level ...
disconnect
Inside disconnect
abhidevmumbai
Connection request from ('127.0.0.1', 45317)
Started thread for client ('127.0.0.1', 45317)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message received ...
Connection closed at TCP level ...
disconnect
Inside disconnect
abhidevmumbai
Connection request from ('127.0.0.1', 45381)
Started thread for client ('127.0.0.1', 45381)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message received ...
Connection request from ('127.0.0.1', 45385)
Started thread for client ('127.0.0.1', 45385)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message from server ...
Message from server ...
Message received ...
Connection closed at TCP level ...
disconnect
Inside disconnect
abhidevmumbai
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "websocket_server.py", line 253, in run
    self.server.client_thread_closed(self)
  File "websocket_server.py", line 393, in client_thread_closed
    self.client_list.remove(client_thread)
  File "websocket_server.py", line 454, in sendall
    "type": "updatechat",
KeyError: 'abhidevmumbai'

Connection request from ('127.0.0.1', 45457)
Started thread for client ('127.0.0.1', 45457)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message from server ...
Message from server ...
Message received ...
Connection closed at TCP level ...
disconnect
Inside disconnect
a
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "websocket_server.py", line 253, in run
    self.server.client_thread_closed(self)
  File "websocket_server.py", line 393, in client_thread_closed
    self.client_list.remove(client_thread)
  File "websocket_server.py", line 454, in sendall
    "type": "updatechat",
KeyError: 'a'

Connection request from ('127.0.0.1', 45530)
Started thread for client ('127.0.0.1', 45530)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message from server ...
Message from server ...
Message received ...
Connection closed at TCP level ...
disconnect
Inside disconnect
a
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "websocket_server.py", line 253, in run
    self.server.client_thread_closed(self)
  File "websocket_server.py", line 393, in client_thread_closed
    self.client_list.remove(client_thread)
  File "websocket_server.py", line 454, in sendall
    "type": "updatechat",
KeyError: 'a'

Connection request from ('127.0.0.1', 45596)
Started thread for client ('127.0.0.1', 45596)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message from server ...
Message from server ...
Message received ...
Connection closed from client ...
Connection closed at TCP level ...
disconnect
Inside disconnect
a
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "websocket_server.py", line 253, in run
    self.server.client_thread_closed(self)
  File "websocket_server.py", line 393, in client_thread_closed
    self.client_list.remove(client_thread)
  File "websocket_server.py", line 454, in sendall
    "type": "updatechat",
KeyError: 'a'

Connection closed at TCP level ...
disconnect
Inside disconnect
abhidevmumbai
Connection request from ('127.0.0.1', 45660)
Started thread for client ('127.0.0.1', 45660)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message received ...
Connection closed at TCP level ...
disconnect
Inside disconnect
abhidevmumbai
Connection request from ('127.0.0.1', 45728)
Started thread for client ('127.0.0.1', 45728)
Websocket handshake request successful ...
Completing websocket handshake ...
Connection opened ...
adduser
Inside adduser
Message from server ...
Message from server ...
Message received ...
